### ISSUE TITLE
打包失败，没有做任何修改

### ISSUE THREAD

**Issue by Mahoo12138** [rev1si0n/bxxt#1]
bxxt [!] bxxt 1.0, Copyright rev1si0n <github.com/rev1si0n/bxxt>, 2019.
bxxt [-] restoring METADATA
bxxt [!] meta-field 'bxxt.extra_cmdline' not set
bxxt [!] meta-field 'bxxt.name' not set
bxxt [-] generating /root/boot_mod.img
bxxt [-] image pagesize is 800
bxxt [*] compress /root/out/kernel, orig: 1dc7000, compressed: a6ec04
bxxt [-] compiling device tree (kernel)
bxxt [+] compiling /root/out/kernel.dts-00
bxxt [*] kernel size: a6ec04, dt size: 3ef76
bxxt [*] appending kernel, size aadb7a (image 800)
bxxt [*] image aligned to aae800, page_size 800
bxxt [-] packaging ramdisk, root path is /root/out/ramdisk
bxxt [*] archive < packing /root/out/ramdisk
bxxt [*] archive < create buffer, 59d199 gussed
bxxt [*] archive < mode=000 .backup
bxxt [*] archive < mode=000 .backup/.magisk
bxxt [*] archive < mode=000 .backup/.rmlist
bxxt [*] archive < mode=750 .backup/init
bxxt [*] archive < mode=755 acct
bxxt [*] archive < mode=777 bin
bxxt [*] archive < mode=777 bugreports
bxxt [*] archive < mode=770 cache
bxxt [*] archive < mode=777 charger
bxxt [*] archive < mode=555 config
bxxt [*] archive < mode=777 d
bxxt [*] archive < mode=771 data
bxxt [*] archive < mode=777 default.prop
bxxt [*] archive < mode=755 dev
bxxt [*] archive < mode=777 dsp
bxxt [*] archive < mode=777 etc
bxxt [*] archive < mode=777 firmware
bxxt [*] archive < mode=750 init
bxxt [*] archive < mode=750 init.environ.rc
bxxt [*] archive < mode=750 init.rc
bxxt [*] archive < mode=750 init.usb.configfs.rc
bxxt [*] archive < mode=750 init.usb.rc
bxxt [*] archive < mode=750 init.zygote32.rc
bxxt [*] archive < mode=750 init.zygote64_32.rc
bxxt [*] archive < mode=755 mnt
bxxt [*] archive < mode=755 odm
bxxt [*] archive < mode=777 odm/app
bxxt [*] archive < mode=777 odm/bin
bxxt [*] archive < mode=777 odm/etc
bxxt [*] archive < mode=777 odm/firmware
bxxt [*] archive < mode=777 odm/framework
bxxt [*] archive < mode=777 odm/lib
bxxt [*] archive < mode=777 odm/lib64
bxxt [*] archive < mode=777 odm/overlay
bxxt [*] archive < mode=777 odm/priv-app
bxxt [*] archive < mode=755 oem
bxxt [*] archive < mode=750 overlay.d
bxxt [*] archive < mode=750 overlay.d/sbin
bxxt [*] archive < mode=644 overlay.d/sbin/magisk32.xz
bxxt [*] archive < mode=644 overlay.d/sbin/magisk64.xz
bxxt [*] archive < mode=777 persist
bxxt [*] archive < mode=755 proc
bxxt [*] archive < mode=777 product
bxxt [*] archive < mode=755 res
bxxt [*] archive < mode=755 res/images
bxxt [*] archive < mode=755 res/images/charger
bxxt [*] archive < mode=644 res/images/charger/battery_fail.png
bxxt [*] archive < mode=644 res/images/charger/battery_scale.png
bxxt [*] archive < mode=750 sbin
bxxt [*] archive < mode=750 sbin/chargeonlymode
bxxt [*] archive < mode=750 sbin/charger
bxxt [*] archive < mode=777 sbin/ueventd
bxxt [*] archive < mode=777 sbin/watchdogd
bxxt [*] archive < mode=777 sdcard
bxxt [*] archive < mode=751 storage
bxxt [*] archive < mode=755 sys
bxxt [*] archive < mode=755 system
bxxt [*] archive < mode=644 ueventd.rc
bxxt [*] archive < mode=755 vendor
bxxt [*] archive < size is 23f502 bytes
bxxt [*] appending ramdisk, size 23f502 (image aae800)
bxxt [*] image aligned to cee000, page_size 800
bxxt [-] compiling device tree (dtb)
bxxt [*] appending dtb, size 0 (image cee000)
bxxt [*] image aligned to cee000, page_size 800
bxxt [-] checking image
bxxt [-] image version is 00, max support 02
bxxt [+] kernel compression 01
bxxt [*] trim (without padding zero bytes) unknown data to size 0
bxxt [-] os version 9.0.0
bxxt [-] detecting device tree
bxxt [*] found device tree #00 ver 11, size 3ef76
bxxt [+] 01 kernel device tree found
bxxt [+] 00 device tree found
bxxt [-] image /root/boot_mod.img generated, size cee000
bxxt [-] finished

原本内核是64M，打包后12M，
Lineage OS Android 9，内核版本 3.18.140

**Comment by rev1si0n** [comment]
镜像小了不一定是失败哦，这种原因大部分是因为：你的boot分区就是64MB，而当你使用dd将镜像读取出来，这个dd出来的镜像就是64MB，但是实际镜像的大小并没有这么多（意思就是文件后面还有多余无用的数据）。举个例子，你的磁盘是200GB，当你dd磁盘出来，直接dd出来的文件也是这个大小，但是实际上里面存的文件并没有这么多。

**Comment by rev1si0n** [comment]
bxxt [] trim (without padding zero bytes) unknown data to size 0 意思就是自动把镜像结尾的00空数据丢掉不处理。
如果不放心的话，下载相同设备及版本的Lineageos并解包，对比下 boot.img 的大小就知道了。

**Comment by Mahoo12138** [comment]
> 镜像小了不一定是失败哦，这种原因大部分是因为：你的boot分区就是64MB，而当你使用dd将镜像读取出来，这个dd出来的镜像就是64MB，但是实际镜像的大小并没有这么多（意思就是文件后面还有多余无用的数据）。举个例子，你的磁盘是200GB，当你dd磁盘出来，直接dd出来的文件也是这个大小，但是实际上里面存的文件并没有这么多。

在此期间已经了解了😂，谢谢你
